version: "3.9"
services:
  db:
    image: postgres:14.2
    container_name: rails-app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    networks:
      - mynetwork

  web:
    image: rails-app_web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-app_web
    command: bash -c "bundle install && yarn install --check-files && rm -f tmp/pids/server.pid && bundle exec pumactl start"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    name: rails-app

volumes:
  pgdata:
    name: rails-app_pgdata
  bundle:
    name: rails-app_bundle
  node_modules:
    name: rails-app_node_modules
