default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: db
  username: root
  password: password

development:
  <<: *default
  database: rails6_dev

test:
  <<: *default
  database: rails6_test